### ISSUE TITLE
Add an amazing icon and name!

### ISSUE THREAD

**Issue by Fohlen** [brandly/Lax#29]
Maybe adding a little icon and name will improve potential for people to remember this.!

**Comment by bitterbit** [comment]
How is this? Feel free to write suggestions 😃 
P.s. really cool project 


![electron-irc-2](https://user-images.githubusercontent.com/4591339/51934175-adc32b80-240b-11e9-9d12-22fca5152e0f.png)

**Comment by brandly** [comment]
@bitterbit oh wow! i just saw this.

> P.s. really cool project

thanks!!

i like the icon! want to send a 512x512 `.png`

**Comment by bitterbit** [comment]
@brandly Yeah sure, I'll send it later today :)

**Comment by bitterbit** [comment]
Sorry for the delay @brandly, attaching some pngs. Update me if you need it in a different format or any other modifications. Hopefully ill have more time this week :) 
![electron-irc-large](https://user-images.githubusercontent.com/4591339/52721250-f228fc80-2fb1-11e9-9984-1c2963eceed1.png)
![electron-irc-medium](https://user-images.githubusercontent.com/4591339/52721251-f228fc80-2fb1-11e9-971b-7c4c780e45b4.png)
![electron-irc-small](https://user-images.githubusercontent.com/4591339/52721590-ac206880-2fb2-11e9-990e-de660639866b.png)

**Comment by bitterbit** [comment]
@brandly I totally missed that you wrote 512px png. here is the image with correct dimensions :)
![electron-irc-512](https://user-images.githubusercontent.com/4591339/53084925-c91de400-353c-11e9-99ea-9b47d53d80cb.png)

**Comment by brandly** [comment]
i meant to do this months ago. this repo is called Lax now. i tried adding the icon to the build, but i couldn't get it working. i'll again soon (or send me a PR if you can get it working!)

maybe updating electron (#73) will help.

**Comment by bitterbit** [comment]
@brandly Let me know if you want the icon in a different format or size
I don't think I'll have time to make a PR though.

**Comment by brandly** [comment]
I think the format is okay, but I’ll let you know. If I remember correctly,
I couldn’t get it to work and no errors were thrown. So I was probably
doing something fundamentally wrong, but I’m not sure what!

**Comment by Fohlen** [comment]
According to this [StackOverflow](https://stackoverflow.com/a/31538436/3135319) entry, one must use [electron-packager](https://github.com/electron/electron-packager) with an `icns` file. You didn't do anything wrong @brandly , just Electron on OSX works differently!

**Comment by brandly** [comment]
oh yeah, i think i tried to create a `icns` but maybe i messed something up there.

this build script was taken from an electron app i worked on years ago. you can see the commented out `--icon`

https://github.com/brandly/Lax/blob/8fd60b123078b90323f555c7176d1755304a76bb/bin/build#L39-L43

i don't remember dealing with `icns` back then, but things have probably changed since. 🤷‍♂

**Comment by brandly** [comment]
@bitterbit this article looks nice: https://elliotekj.com/2014/05/27/how-to-create-high-resolution-icns-files/

you have this logo in some kind of vector format? would it be easy to export all these image sizes? 

i think it'd be nice to get this icon in. the app looks pretty good these days, and we're generating new `.app` releases via GitHub actions thanks to @Fohlen. this repo's getting fairly polished!

**Comment by bitterbit** [comment]
@brandly No problem! I hope I'll get to it tonight

**Comment by brandly** [comment]
whenever you get a chance!

**Comment by bitterbit** [comment]
First time I ever did this, @brandly let me know if it works :) 
The icon.icns.zip has the icns file, and Archive.zip has pdf and svg versions. 

[Archive.zip](https://github.com/brandly/Lax/files/4063530/Archive.zip)
[icon.icns.zip](https://github.com/brandly/Lax/files/4063519/icon.icns.zip)

**Comment by brandly** [comment]
so i tagged a release. github actions created a build: https://github.com/brandly/Lax/releases/tag/v0.6.1

the icon shows up in finder! very cool

<img width="274" alt="Screen Shot 2020-01-15 at 11 53 18 AM" src="https://user-images.githubusercontent.com/820696/72454420-d49a7f00-378e-11ea-8bc7-770b91a1be70.png">

but the dock still shows the default

<img width="118" alt="Screen Shot 2020-01-15 at 12 02 44 PM" src="https://user-images.githubusercontent.com/820696/72454499-f7c52e80-378e-11ea-8a6b-e85a7a4f45e3.png">

[looks like there's more to do?](https://stackoverflow.com/a/57346329/1614967) seems odd

thanks for the assets!!!

**Comment by Fohlen** [comment]
weird but ok. can you add those fixes @brandly ?

**Comment by bitterbit** [comment]
Awesome!

**Comment by brandly** [comment]
it shows up in notifications!

<img width="365" alt="Screen Shot 2020-01-15 at 6 24 43 PM" src="https://user-images.githubusercontent.com/820696/72480132-683a7280-37c4-11ea-8454-3eec00ae6824.png">

yeah, i'll figure out the tray icon. i think it wants a png, so i'll take one that was posted above

**Comment by brandly** [comment]
[v0.6.2](https://github.com/brandly/Lax/releases/tag/v0.6.2) 🎉
