### ISSUE TITLE
Automatically switch to dark mode using Ambient Light Sensor API

### ISSUE THREAD

**Issue by Fohlen** [brandly/Lax#79]
Use [Ambient Light Sensor API](https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Sensor_API) by enabling the `experimentalFeatures ` flag in `BrowserWindow` to determine dark mode. Also see [this demo](https://github.com/ananyaneogi/dark-theme).

**Comment by brandly** [comment]
i'm under the impression that the OS can do this.

> [use Settings to make their devices automatically switch to Dark Mode when ambient light is low.](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/)

currently, we initialize to dark mode based on OS settings, but then we store the selection in `localStorage` and use whatever's there. this means Lax's setting trumps the OS setting, which is maybe a mistake.

if we want to support ambient light, i think we leave the dark mode decision to the OS, wire up change events in case the OS switches to dark mode while Lax is running, and then leave the rest up to the OS. i'd rather not complicate application code, and i'm not even sure Electron supports this.
