### ISSUE TITLE
links not working correctly

### ISSUE THREAD

**Issue by brandly** [brandly/Lax#89]
i clicked a link someone shared. it took over the electron window instead of opening (safely) in a browser

i was using the v0.6.4 build

**Comment by srirangan** [comment]
Yep, I see this as well. I don't mind the behavior, as long as there's a back button.

But I guess the expected behavior is to open in default browser.

**Comment by brandly** [comment]
> But I guess the expected behavior is to open in default browser.

Yes! I swear it used to behave like this. I don’t think I’ve touched anything over there in a while, so maybe updating Electron itself broke it. It’s probably not a difficult fix.

**Comment by srirangan** [comment]
I see you're using `shell.openExternal` which seems correct. Perhaps the event is bubbling up to `react-linkify` nevertheless.

**Comment by srirangan** [comment]
Curious if we need `handleLink()` at all. Does does passing `target: '_blank'` not behave within the Electron shell?

**Comment by brandly** [comment]
@srirangan thanks for chiming in, helped motivate me to actually do something lol

[the latest version of `react-linkfy` doesn't seem to take a `properties` prop at all.](https://github.com/tasti/react-linkify/blob/e751f7377bc30cfa1515f6ccea37f9f6f7da3f6e/src/Linkify.jsx) instead of figuring out if there's a new approach, i just rolled back.

after rolling back, i tried the `target: '_blank'` approach, since i thought that'd be nice. however, that opened a second electron window with the site in it. with `openExternal`, it takes you to your real browser.

**Comment by brandly** [comment]
Lax `v0.6.5` should be out soon. try it out and lmk if it works well for you. thanks again! ✨

**Comment by srirangan** [comment]
Thank you @brandly
