### ISSUE TITLE
Able to highlight UI elements

### ISSUE THREAD

**Issue by MitchTalmadge** [brandly/Lax#97]
It's possible to highlight text in the UI that you wouldn't expect. For example: (top left)

![image](https://user-images.githubusercontent.com/8848080/92439961-f8209880-f168-11ea-9834-fe3d8fdf6ed2.png)

I think it's pretty easy to disable this by adding the `user-select: none;` style to elements that shouldn't be highlighted.

Could potentially do it application-wide as seen here: https://github.com/electron/electron/issues/2538, then just re-add support for highlighting in places you'd expect it to work (like chat history).

**Comment by brandly** [comment]
looks like this is the only place i'm locking things down (with the unnecessary prefix):

https://github.com/brandly/Lax/blob/b66850a8de4799d827d62fd0ee6af96c35341d46/src/sass/components/channel-list.scss#L10-L14

> just re-add support for highlighting in places you'd expect it to work

i think this makes a lot of sense. in web apps, not being able to select text is the exception, but it's the default in desktop apps.

**Comment by MitchTalmadge** [comment]
Yeah! Maybe I will get time to improve this.
